"""WebSocket connection management and event handling."""

from server.websocket.events import (
    AgentCompletePayload,
    AgentInfo,
    AgentRegisteredPayload,
    AgentStreamingPayload,
    AgentThinkingPayload,
    ClientEventType,
    ClientMessage,
    ConfidenceUpdatePayload,
    ConnectedPayload,
    CritiqueData,
    DraftSectionUpdate,
    DraftUpdatePayload,
    ErrorPayload,
    EscalationPayload,
    GenerationCompletePayload,
    GenerationControlPayload,
    GenerationErrorPayload,
    GenerationStartedPayload,
    GenerationStartPayload,
    PhaseChangePayload,
    ResponseData,
    RoundEndPayload,
    RoundStartPayload,
    ServerEventType,
    ServerMessage,
    WebSocketMessage,
    create_error_message,
    create_server_message,
)
from server.websocket.handler import (
    EventHandler,
    GenerationHandlerMixin,
    WebSocketHandler,
    broadcast_generation_event,
    subscribe_connection_to_generation,
    validate_generation_control_payload,
    validate_generation_start_payload,
)
from server.websocket.manager import Connection, ConnectionManager, connection_manager

__all__ = [
    # Event types
    "ClientEventType",
    "ServerEventType",
    # Message types
    "WebSocketMessage",
    "ClientMessage",
    "ServerMessage",
    # Payloads - Client
    "GenerationStartPayload",
    "GenerationControlPayload",
    # Payloads - Server
    "ConnectedPayload",
    "RoundStartPayload",
    "RoundEndPayload",
    "PhaseChangePayload",
    "AgentInfo",
    "AgentRegisteredPayload",
    "AgentThinkingPayload",
    "AgentStreamingPayload",
    "CritiqueData",
    "ResponseData",
    "AgentCompletePayload",
    "DraftSectionUpdate",
    "DraftUpdatePayload",
    "ConfidenceUpdatePayload",
    "EscalationPayload",
    "GenerationStartedPayload",
    "GenerationCompletePayload",
    "GenerationErrorPayload",
    "ErrorPayload",
    # Helper functions
    "create_server_message",
    "create_error_message",
    # Connection management
    "Connection",
    "ConnectionManager",
    "connection_manager",
    # Handler
    "EventHandler",
    "WebSocketHandler",
    "GenerationHandlerMixin",
    "validate_generation_start_payload",
    "validate_generation_control_payload",
    "subscribe_connection_to_generation",
    "broadcast_generation_event",
]
